### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by MingfeiCh** [ppwwyyxx/Adversarial-Face-Attack#3]
Can you explain why you use `noise = 0.9 * grad + noise` instead of `grad = 0.9 * grad + noise` in `line 94 `of `face_attack.py`?

Thank you!

**Comment by ppwwyyxx** [comment]
Changing the line to `grad = 0.9 * grad + noise` will make it useless because the variable `grad` is not used after that line.

**Comment by MingfeiCh** [comment]
Oh, I understand this operation! Thanks for your reply!
