### ISSUE TITLE
Could you explain where is the lfw and align package in face_attack.py?

### ISSUE THREAD

**Issue by zhoufengfan** [ppwwyyxx/Adversarial-Face-Attack#6]
In the `face_attack.py`, there is 2 line of code:
``` python
import lfw as lfw
import align.detect_face as FaceDet
```

But I don't know where is the lfw and align package.
Could you explain where is the lfw and align package in face_attack.py?

**Comment by ppwwyyxx** [comment]
Follow step 2 in the readme: https://github.com/ppwwyyxx/Adversarial-Face-Attack#preparation-to-use-the-code
