### ISSUE TITLE
How to understand the dist

### ISSUE THREAD

**Issue by PPPPPPPeng** [ppwwyyxx/Adversarial-Face-Attack#7]
dist = np.dot(emb, self.victim_embeddings.T).flatten()

how to understand the dist line, it's a somewhat formula?And whether I got wrong in the following steps ?:
I change the dist to calculate cosine similarity dist, but I found most dist of the original images results is close to 0, and most of most is lower than 0( I think I got wrong with this,normal image pair's cosine similarity is [0,0.5],and the dist result of adversarial examples is close to 0.8 or higher

**Comment by ppwwyyxx** [comment]
embeddings are L2 normalized, so `dist = np.dot(emb, self.victim_embeddings.T).flatten()` already computes cosine similarity.
